"""Rename private_message -> private_messages

Revision ID: 0b2e41b6a5d3
Revises: 4d003a683656
Create Date: 2025-07-26 06:44:50.285753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b2e41b6a5d3'
down_revision = '4d003a683656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent', sa.DateTime(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('read_sender', sa.Boolean(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('deleted_sender', sa.Boolean(), nullable=False),
    sa.Column('deleted_recipient', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('private_message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('from_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('read_sender', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_sender', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_recipient', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('private_message_from_user_id_fkey')),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('private_message_to_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('private_message_pkey'))
    )
    op.drop_table('private_messages')
    # ### end Alembic commands ###
