"""Add changed_first_password column

Revision ID: 375ed1b7df54
Revises: 859b810c3025
Create Date: 2025-07-19 16:45:27.642880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375ed1b7df54'
down_revision = '859b810c3025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changed_first_password', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('changed_first_password')

    # ### end Alembic commands ###
