"""Add left in membership

Revision ID: 490711c3f64d
Revises: b0f816ac3c5d
Create Date: 2025-07-20 13:09:08.108988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490711c3f64d'
down_revision = 'b0f816ac3c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('left', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_column('left')

    # ### end Alembic commands ###
