"""Add deleted for messages

Revision ID: 4d003a683656
Revises: dd94a5edd231
Create Date: 2025-07-25 15:37:50.359720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d003a683656'
down_revision = 'dd94a5edd231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_sender', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deleted_recipient', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_message', schema=None) as batch_op:
        batch_op.drop_column('deleted_recipient')
        batch_op.drop_column('deleted_sender')

    # ### end Alembic commands ###
