"""Remove unique on member email

Revision ID: 859b810c3025
Revises: 3332fbc87357
Create Date: 2025-07-19 11:50:15.083780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859b810c3025'
down_revision = '3332fbc87357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('members_email_key'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('members_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
