"""Set changed_first_password to not nullable

Revision ID: b0f816ac3c5d
Revises: 375ed1b7df54
Create Date: 2025-07-19 16:46:30.843259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f816ac3c5d'
down_revision = '375ed1b7df54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('changed_first_password',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('changed_first_password',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
