"""Create user role

Revision ID: b94fb954c567
Revises: c79401bb5a0b
Create Date: 2025-07-22 08:15:41.510936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94fb954c567'
down_revision = 'c79401bb5a0b'
branch_labels = None
depends_on = None


userroleenum = sa.Enum('ADMIN', 'USER', name='userroleenum')

def upgrade():
    userroleenum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', userroleenum, nullable=True))

    op.execute("UPDATE users SET role= 'USER'")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
