"""Add contact card

Revision ID: c79401bb5a0b
Revises: 214f6160d6b7
Create Date: 2025-07-21 17:39:07.544425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79401bb5a0b'
down_revision = '214f6160d6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=255), nullable=False),
    sa.Column('interest', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('handled', sa.DateTime(), nullable=True),
    sa.Column('handled_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_card')
    # ### end Alembic commands ###
