"""Add read_sender

Revision ID: dd94a5edd231
Revises: ff6a2f70b976
Create Date: 2025-07-25 15:12:30.852334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd94a5edd231'
down_revision = 'ff6a2f70b976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_sender', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_message', schema=None) as batch_op:
        batch_op.drop_column('read_sender')

    # ### end Alembic commands ###
